Global everquest_process_handle := 0
Global everquest_process_id     := 0

Global EVERQUEST_CLIENT := "eqgame.exe"

Global EVERQUEST_TITLE := "EverQuest"

Global EVERQUEST_BASE_ADDRESS := 0x00400000

Global EVERQUEST_CAMERA_POINTER := EVERQUEST_BASE_ADDRESS + 0x69DF08 ; POINTER to STRUCT
Global EVERQUEST_OFFSET_CAMERA_Y       := 0x04 ; FLOAT
Global EVERQUEST_OFFSET_CAMERA_X       := 0x08 ; FLOAT
Global EVERQUEST_OFFSET_CAMERA_Z       := 0x0C ; FLOAT
Global EVERQUEST_OFFSET_CAMERA_HEADING := 0x10 ; FLOAT
Global EVERQUEST_OFFSET_CAMERA_PITCH   := 0x14 ; FLOAT

Global EVERQUEST_ASM_SET_CAMERA_Y       := EVERQUEST_BASE_ADDRESS + 0x288B4B ; 89 4F 04 - mov [edi+04],ecx
Global EVERQUEST_ASM_SET_CAMERA_X       := EVERQUEST_BASE_ADDRESS + 0x288B51 ; 89 57 08 - mov [edi+08],edx
Global EVERQUEST_ASM_SET_CAMERA_Z       := EVERQUEST_BASE_ADDRESS + 0x288B57 ; 89 47 0C - mov [edi+0C],eax
Global EVERQUEST_ASM_SET_CAMERA_HEADING := EVERQUEST_BASE_ADDRESS + 0x288C23 ; 89 4F 10 - mov [edi+10],ecx
Global EVERQUEST_ASM_SET_CAMERA_PITCH   := EVERQUEST_BASE_ADDRESS + 0x288C2C ; 89 57 14 - mov [edi+14],edx
Global EVERQUEST_ASM_SET_CAMERA_Y_2     := EVERQUEST_BASE_ADDRESS + 0x685E2  ; 89 08    - mov [eax],ecx
Global EVERQUEST_ASM_SET_CAMERA_X_2     := EVERQUEST_BASE_ADDRESS + 0x685F0  ; 89 10    - mov [eax],edx
Global EVERQUEST_ASM_SET_CAMERA_Z_2     := EVERQUEST_BASE_ADDRESS + 0x685FE  ; 89 08    - mov [eax],ecx
Global EVERQUEST_ASM_SET_CAMERA_Z_3     := EVERQUEST_BASE_ADDRESS + 0x288B83 ; D9 1B    - fstp dword ptr [ebx]
Global EVERQUEST_ASM_SET_CAMERA_Z_4     := EVERQUEST_BASE_ADDRESS + 0x288BE1 ; D9 1B    - fstp dword ptr [ebx]
Global EVERQUEST_ASM_SET_CAMERA_PITCH_2 := EVERQUEST_BASE_ADDRESS + 0x288C4D ; D9 5F 14 - fstp dword ptr [edi+14]

Global EVERQUEST_ASM_SET_CAMERA_Y_BYTES       := "89,4F,04"
Global EVERQUEST_ASM_SET_CAMERA_X_BYTES       := "89,57,08"
Global EVERQUEST_ASM_SET_CAMERA_Z_BYTES       := "89,47,0C"
Global EVERQUEST_ASM_SET_CAMERA_HEADING_BYTES := "89,4F,10"
Global EVERQUEST_ASM_SET_CAMERA_PITCH_BYTES   := "89,57,14"
Global EVERQUEST_ASM_SET_CAMERA_Y_2_BYTES     := "89,08"
Global EVERQUEST_ASM_SET_CAMERA_X_2_BYTES     := "89,10"
Global EVERQUEST_ASM_SET_CAMERA_Z_2_BYTES     := "89,08"
Global EVERQUEST_ASM_SET_CAMERA_Z_3_BYTES     := "D9,1B"
Global EVERQUEST_ASM_SET_CAMERA_Z_4_BYTES     := "D9,1B"
Global EVERQUEST_ASM_SET_CAMERA_PITCH_2_BYTES := "D9,5F,14"

Global EVERQUEST_ASM_SET_CAMERA_Y_SIZE       := 3
Global EVERQUEST_ASM_SET_CAMERA_Z_SIZE       := 3
Global EVERQUEST_ASM_SET_CAMERA_X_SIZE       := 3
Global EVERQUEST_ASM_SET_CAMERA_HEADING_SIZE := 3
Global EVERQUEST_ASM_SET_CAMERA_PITCH_SIZE   := 3
Global EVERQUEST_ASM_SET_CAMERA_Y_2_SIZE     := 2
Global EVERQUEST_ASM_SET_CAMERA_X_2_SIZE     := 2
Global EVERQUEST_ASM_SET_CAMERA_Z_2_SIZE     := 2
Global EVERQUEST_ASM_SET_CAMERA_Z_3_SIZE     := 2
Global EVERQUEST_ASM_SET_CAMERA_Z_4_SIZE     := 2
Global EVERQUEST_ASM_SET_CAMERA_PITCH_2_SIZE := 3

Global EVERQUEST_CAMERA_PITCH_DEFAULT := -8.5 ; 119.5 + 8.5 = 128 everquest degrees = 90 degrees

Global EVERQUEST_CAMERA_PITCH_MIN := -119.5 ; -136.5
Global EVERQUEST_CAMERA_PITCH_MAX := 119.5

Global EVERQUEST_CAMERA_VIEW := EVERQUEST_BASE_ADDRESS + 0x5E6714 ; DWORD ; EVERQUEST_CAMERA_VIEW_x

Global EVERQUEST_CAMERA_VIEW_FIRST_PERSON   := 0
Global EVERQUEST_CAMERA_VIEW_THIRD_PERSON_1 := 1
Global EVERQUEST_CAMERA_VIEW_THIRD_PERSON_2 := 2
Global EVERQUEST_CAMERA_VIEW_THIRD_PERSON_3 := 3
Global EVERQUEST_CAMERA_VIEW_THIRD_PERSON_4 := 4
Global EVERQUEST_CAMERA_VIEW_THIRD_PERSON_5 := 5
Global EVERQUEST_CAMERA_VIEW_THIRD_PERSON_OVERHEAD := EVERQUEST_CAMERA_VIEW_THIRD_PERSON_1
Global EVERQUEST_CAMERA_VIEW_THIRD_PERSON_CHASE    := EVERQUEST_CAMERA_VIEW_THIRD_PERSON_2
Global EVERQUEST_CAMERA_VIEW_THIRD_PERSON_TETHER   := EVERQUEST_CAMERA_VIEW_THIRD_PERSON_5

Global EVERQUEST_CAMERA_HEADING_MIN := 0
Global EVERQUEST_CAMERA_HEADING_MAX := 512

everquest_GetCameraPointer()
{
    camera := Memory_Read(everquest_process_handle, EVERQUEST_CAMERA_POINTER)

    Return, camera
}
